window.DACOSCDM_DATA = {
  "sheet": "DatosCdM",
  "rows": [
    {
      "seccion": "resumen",
      "id": "gasto_medio_diario_persona",
      "indicador": "Gasto medio diario por persona",
      "valor": "168.0",
      "unidad": "EUR/dia",
      "periodo": "2025-05",
      "periodo_comparacion": "2024-05",
      "valor_comparacion": "160.0",
      "variacion_pct": "5.0",
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "EGATUR / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "resumen",
      "id": "estancia_media",
      "indicador": "Estancia media",
      "valor": "2.21",
      "unidad": "noches",
      "periodo": "2025-05",
      "periodo_comparacion": "2024-05",
      "valor_comparacion": "2.10",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "EOH / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "resumen",
      "id": "ocupacion_hotelera",
      "indicador": "Ocupacion hotelera",
      "valor": "53.05",
      "unidad": "porcentaje",
      "periodo": "2025-05",
      "periodo_comparacion": "2024-05",
      "valor_comparacion": "55.10",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "EOH_PUNT_TUR / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "resumen",
      "id": "adr",
      "indicador": "ADR hotelero",
      "valor": "103.93",
      "unidad": "EUR",
      "periodo": "2025-05",
      "periodo_comparacion": "2024-05",
      "valor_comparacion": "103.64",
      "variacion_pct": "0.28",
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Precios hoteleros / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "resumen",
      "id": "revpar",
      "indicador": "RevPAR",
      "valor": "71.04",
      "unidad": "EUR",
      "periodo": "2025-05",
      "periodo_comparacion": "2024-05",
      "valor_comparacion": "67.43",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "EOH / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "mercados",
      "id": "peso_mercado",
      "indicador": "Peso del mercado",
      "valor": "15.47",
      "unidad": "porcentaje",
      "periodo": "2025-05",
      "periodo_comparacion": "2024-05",
      "valor_comparacion": "12.22",
      "variacion_pct": null,
      "nivel": "mercado",
      "segmento": "Francia",
      "fuente_dataset": "TURISMO_RECEPTOR_MUN_PAIS / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "mercados",
      "id": "peso_mercado",
      "indicador": "Peso del mercado",
      "valor": "14.81",
      "unidad": "porcentaje",
      "periodo": "2025-05",
      "periodo_comparacion": "2024-05",
      "valor_comparacion": "19.06",
      "variacion_pct": null,
      "nivel": "mercado",
      "segmento": "Reino Unido",
      "fuente_dataset": "TURISMO_RECEPTOR_MUN_PAIS / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "mercados",
      "id": "peso_mercado",
      "indicador": "Peso del mercado",
      "valor": "5.78",
      "unidad": "porcentaje",
      "periodo": "2025-05",
      "periodo_comparacion": "2024-05",
      "valor_comparacion": null,
      "variacion_pct": null,
      "nivel": "mercado",
      "segmento": "Italia",
      "fuente_dataset": "TURISMO_RECEPTOR_MUN_PAIS / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "mercados",
      "id": "peso_mercado",
      "indicador": "Peso del mercado",
      "valor": "9.91",
      "unidad": "porcentaje",
      "periodo": "2025-05",
      "periodo_comparacion": "2024-05",
      "valor_comparacion": "9.35",
      "variacion_pct": null,
      "nivel": "mercado",
      "segmento": "Alemania",
      "fuente_dataset": "TURISMO_RECEPTOR_MUN_PAIS / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "alojamiento",
      "id": "plazas_hoteleras",
      "indicador": "Plazas hoteleras disponibles",
      "valor": 3956,
      "unidad": "plazas",
      "periodo": "2025-05",
      "periodo_comparacion": "2024-05",
      "valor_comparacion": 3709,
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "EOH_PUNT_TUR / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "alojamiento",
      "id": "establecimientos_abiertos",
      "indicador": "Establecimientos hoteleros abiertos",
      "valor": 40,
      "unidad": "establecimientos",
      "periodo": "2025-05",
      "periodo_comparacion": "2024-05",
      "valor_comparacion": 37,
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "EOH_PUNT_TUR / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "accesibilidad",
      "id": "pasajeros_aereos",
      "indicador": "Pasajeros aereos con destino Jerez de la Frontera",
      "valor": 99614,
      "unidad": "pasajeros",
      "periodo": "2025-05",
      "periodo_comparacion": "2024-05",
      "valor_comparacion": 102737,
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "AENA_DESTINOS / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "estancia_media",
      "indicador": "Estancia media",
      "valor": "2.27",
      "unidad": "noches",
      "periodo": "2024-06",
      "periodo_comparacion": "2023-06",
      "valor_comparacion": "2.39",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "estancia_media",
      "indicador": "Estancia media",
      "valor": "2.42",
      "unidad": "noches",
      "periodo": "2024-07",
      "periodo_comparacion": "2023-07",
      "valor_comparacion": "2.25",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "estancia_media",
      "indicador": "Estancia media",
      "valor": "2.71",
      "unidad": "noches",
      "periodo": "2024-08",
      "periodo_comparacion": "2023-08",
      "valor_comparacion": "2.60",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "estancia_media",
      "indicador": "Estancia media",
      "valor": "2.31",
      "unidad": "noches",
      "periodo": "2024-09",
      "periodo_comparacion": "2023-09",
      "valor_comparacion": "1.97",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "estancia_media",
      "indicador": "Estancia media",
      "valor": "2.18",
      "unidad": "noches",
      "periodo": "2024-10",
      "periodo_comparacion": "2023-10",
      "valor_comparacion": "2.06",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "estancia_media",
      "indicador": "Estancia media",
      "valor": "2.25",
      "unidad": "noches",
      "periodo": "2024-11",
      "periodo_comparacion": "2023-11",
      "valor_comparacion": "2.01",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "estancia_media",
      "indicador": "Estancia media",
      "valor": "1.86",
      "unidad": "noches",
      "periodo": "2024-12",
      "periodo_comparacion": "2023-12",
      "valor_comparacion": "1.93",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "estancia_media",
      "indicador": "Estancia media",
      "valor": "2.45",
      "unidad": "noches",
      "periodo": "2025-01",
      "periodo_comparacion": "2024-01",
      "valor_comparacion": "1.84",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "estancia_media",
      "indicador": "Estancia media",
      "valor": "2.33",
      "unidad": "noches",
      "periodo": "2025-02",
      "periodo_comparacion": "2024-02",
      "valor_comparacion": "2.00",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "estancia_media",
      "indicador": "Estancia media",
      "valor": "2.46",
      "unidad": "noches",
      "periodo": "2025-03",
      "periodo_comparacion": "2024-03",
      "valor_comparacion": "2.18",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "estancia_media",
      "indicador": "Estancia media",
      "valor": "2.74",
      "unidad": "noches",
      "periodo": "2025-04",
      "periodo_comparacion": "2024-04",
      "valor_comparacion": "2.39",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "estancia_media",
      "indicador": "Estancia media",
      "valor": "2.21",
      "unidad": "noches",
      "periodo": "2025-05",
      "periodo_comparacion": "2024-05",
      "valor_comparacion": "2.10",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "ocupacion_hotelera",
      "indicador": "Ocupacion hotelera",
      "valor": "51.21",
      "unidad": "porcentaje",
      "periodo": "2024-06",
      "periodo_comparacion": "2023-06",
      "valor_comparacion": "51.15",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "ocupacion_hotelera",
      "indicador": "Ocupacion hotelera",
      "valor": "65.15",
      "unidad": "porcentaje",
      "periodo": "2024-07",
      "periodo_comparacion": "2023-07",
      "valor_comparacion": "60.45",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "ocupacion_hotelera",
      "indicador": "Ocupacion hotelera",
      "valor": "76.64",
      "unidad": "porcentaje",
      "periodo": "2024-08",
      "periodo_comparacion": "2023-08",
      "valor_comparacion": "70.63",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "ocupacion_hotelera",
      "indicador": "Ocupacion hotelera",
      "valor": "57.07",
      "unidad": "porcentaje",
      "periodo": "2024-09",
      "periodo_comparacion": "2023-09",
      "valor_comparacion": "56.07",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "ocupacion_hotelera",
      "indicador": "Ocupacion hotelera",
      "valor": "54.04",
      "unidad": "porcentaje",
      "periodo": "2024-10",
      "periodo_comparacion": "2023-10",
      "valor_comparacion": "54.81",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "ocupacion_hotelera",
      "indicador": "Ocupacion hotelera",
      "valor": "48.84",
      "unidad": "porcentaje",
      "periodo": "2024-11",
      "periodo_comparacion": "2023-11",
      "valor_comparacion": "42.24",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "ocupacion_hotelera",
      "indicador": "Ocupacion hotelera",
      "valor": "42.59",
      "unidad": "porcentaje",
      "periodo": "2024-12",
      "periodo_comparacion": "2023-12",
      "valor_comparacion": "45.47",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "ocupacion_hotelera",
      "indicador": "Ocupacion hotelera",
      "valor": "32.76",
      "unidad": "porcentaje",
      "periodo": "2025-01",
      "periodo_comparacion": "2024-01",
      "valor_comparacion": "32.94",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "ocupacion_hotelera",
      "indicador": "Ocupacion hotelera",
      "valor": "44.46",
      "unidad": "porcentaje",
      "periodo": "2025-02",
      "periodo_comparacion": "2024-02",
      "valor_comparacion": "42.96",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "ocupacion_hotelera",
      "indicador": "Ocupacion hotelera",
      "valor": "45.95",
      "unidad": "porcentaje",
      "periodo": "2025-03",
      "periodo_comparacion": "2024-03",
      "valor_comparacion": "49.68",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "ocupacion_hotelera",
      "indicador": "Ocupacion hotelera",
      "valor": "45.62",
      "unidad": "porcentaje",
      "periodo": "2025-04",
      "periodo_comparacion": "2024-04",
      "valor_comparacion": "52.77",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "ocupacion_hotelera",
      "indicador": "Ocupacion hotelera",
      "valor": "53.05",
      "unidad": "porcentaje",
      "periodo": "2025-05",
      "periodo_comparacion": "2024-05",
      "valor_comparacion": "55.10",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "adr",
      "indicador": "ADR hotelero",
      "valor": "81.33",
      "unidad": "EUR",
      "periodo": "2024-06",
      "periodo_comparacion": "2023-06",
      "valor_comparacion": "76.93",
      "variacion_pct": "2.13",
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "adr",
      "indicador": "ADR hotelero",
      "valor": "81.99",
      "unidad": "EUR",
      "periodo": "2024-07",
      "periodo_comparacion": "2023-07",
      "valor_comparacion": "81.59",
      "variacion_pct": "0.49",
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "adr",
      "indicador": "ADR hotelero",
      "valor": "96.00",
      "unidad": "EUR",
      "periodo": "2024-08",
      "periodo_comparacion": "2023-08",
      "valor_comparacion": "91.23",
      "variacion_pct": "5.23",
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "adr",
      "indicador": "ADR hotelero",
      "valor": "84.25",
      "unidad": "EUR",
      "periodo": "2024-09",
      "periodo_comparacion": "2023-09",
      "valor_comparacion": "76.41",
      "variacion_pct": "10.26",
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "adr",
      "indicador": "ADR hotelero",
      "valor": "79.78",
      "unidad": "EUR",
      "periodo": "2024-10",
      "periodo_comparacion": "2023-10",
      "valor_comparacion": "81.57",
      "variacion_pct": -2.19,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "adr",
      "indicador": "ADR hotelero",
      "valor": "79.80",
      "unidad": "EUR",
      "periodo": "2024-11",
      "periodo_comparacion": "2023-11",
      "valor_comparacion": "74.63",
      "variacion_pct": "6.93",
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "adr",
      "indicador": "ADR hotelero",
      "valor": "78.21",
      "unidad": "EUR",
      "periodo": "2024-12",
      "periodo_comparacion": "2023-12",
      "valor_comparacion": "81.02",
      "variacion_pct": -3.47,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "adr",
      "indicador": "ADR hotelero",
      "valor": "81.54",
      "unidad": "EUR",
      "periodo": "2025-01",
      "periodo_comparacion": "2024-01",
      "valor_comparacion": "73.99",
      "variacion_pct": "10.20",
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "adr",
      "indicador": "ADR hotelero",
      "valor": "74.25",
      "unidad": "EUR",
      "periodo": "2025-02",
      "periodo_comparacion": "2024-02",
      "valor_comparacion": "81.91",
      "variacion_pct": -9.35,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "adr",
      "indicador": "ADR hotelero",
      "valor": "71.76",
      "unidad": "EUR",
      "periodo": "2025-03",
      "periodo_comparacion": "2024-03",
      "valor_comparacion": "80.09",
      "variacion_pct": -10.4,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "adr",
      "indicador": "ADR hotelero",
      "valor": "100.82",
      "unidad": "EUR",
      "periodo": "2025-04",
      "periodo_comparacion": "2024-04",
      "valor_comparacion": "119.92",
      "variacion_pct": -15.93,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "adr",
      "indicador": "ADR hotelero",
      "valor": "103.93",
      "unidad": "EUR",
      "periodo": "2025-05",
      "periodo_comparacion": "2024-05",
      "valor_comparacion": "103.64",
      "variacion_pct": "0.28",
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "revpar",
      "indicador": "RevPAR",
      "valor": "52.21",
      "unidad": "EUR",
      "periodo": "2024-06",
      "periodo_comparacion": "2023-06",
      "valor_comparacion": "54.21",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "revpar",
      "indicador": "RevPAR",
      "valor": "58.05",
      "unidad": "EUR",
      "periodo": "2024-07",
      "periodo_comparacion": "2023-07",
      "valor_comparacion": "56.09",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "revpar",
      "indicador": "RevPAR",
      "valor": "77.95",
      "unidad": "EUR",
      "periodo": "2024-08",
      "periodo_comparacion": "2023-08",
      "valor_comparacion": "71.61",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "revpar",
      "indicador": "RevPAR",
      "valor": "60.00",
      "unidad": "EUR",
      "periodo": "2024-09",
      "periodo_comparacion": "2023-09",
      "valor_comparacion": "50.59",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "revpar",
      "indicador": "RevPAR",
      "valor": "57.33",
      "unidad": "EUR",
      "periodo": "2024-10",
      "periodo_comparacion": "2023-10",
      "valor_comparacion": "59.91",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "revpar",
      "indicador": "RevPAR",
      "valor": "49.79",
      "unidad": "EUR",
      "periodo": "2024-11",
      "periodo_comparacion": "2023-11",
      "valor_comparacion": "42.31",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "revpar",
      "indicador": "RevPAR",
      "valor": "38.55",
      "unidad": "EUR",
      "periodo": "2024-12",
      "periodo_comparacion": "2023-12",
      "valor_comparacion": "42.36",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "revpar",
      "indicador": "RevPAR",
      "valor": "40.42",
      "unidad": "EUR",
      "periodo": "2025-01",
      "periodo_comparacion": "2024-01",
      "valor_comparacion": "30.15",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "revpar",
      "indicador": "RevPAR",
      "valor": "46.25",
      "unidad": "EUR",
      "periodo": "2025-02",
      "periodo_comparacion": "2024-02",
      "valor_comparacion": "49.09",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "revpar",
      "indicador": "RevPAR",
      "valor": "43.59",
      "unidad": "EUR",
      "periodo": "2025-03",
      "periodo_comparacion": "2024-03",
      "valor_comparacion": "50.02",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "revpar",
      "indicador": "RevPAR",
      "valor": "65.35",
      "unidad": "EUR",
      "periodo": "2025-04",
      "periodo_comparacion": "2024-04",
      "valor_comparacion": "85.46",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    },
    {
      "seccion": "historico_mensual",
      "id": "revpar",
      "indicador": "RevPAR",
      "valor": "71.04",
      "unidad": "EUR",
      "periodo": "2025-05",
      "periodo_comparacion": "2024-05",
      "valor_comparacion": "67.43",
      "variacion_pct": null,
      "nivel": "destino",
      "segmento": null,
      "fuente_dataset": "Serie historica / modelo demo",
      "fuente_url": "https://www.dataestur.es/apidata/",
      "calidad_dato": "demo_no_oficial"
    }
  ]
};
