window.SIM_DIAG_TURISTA = {
  "sheet": "Sim. Diagnostico Turista",
  "headers": [
    "ID",
    "Q1 Procedencia",
    "Q2 Edad",
    "Q3 Sexo",
    "Q4 Nivel ingresos",
    "Q5 Relacion con el vino",
    "Q6 Compañia de viaje",
    "Q7 Noches en Jerez",
    "Q8 Frecuencia de visita",
    "Q9 Actividades realizadas",
    "Q10 Medio de transporte",
    "Q11 Alojamiento",
    "Q12 Oferta gastronomica",
    "Q13 Gasto por persona (visita+cata)",
    "Q14 % gasto en vino/bodegas",
    "Q15 Medios de inspiracion",
    "Q16 Motivo principal de la visita",
    "Q17 Destino alternativo",
    "Q18 Satisfaccion global (1-5)",
    "Q19a Transporte/señalizacion (1-5)",
    "Q19b Alojamiento (1-5)",
    "Q19c Gastronomia (1-5)",
    "Q19d Calidad-precio (1-5)",
    "Q19e Atencion en bodega (1-5)",
    "Q20 Aspecto mas positivo",
    "Q21 Aspecto a mejorar",
    "Q22 NPS (0-10)",
    "Q23 Intencion de repetir"
  ],
  "rows": [
    {
      "ID": "R001",
      "Q1 Procedencia": "España - Cataluña",
      "Q2 Edad": "45-54",
      "Q3 Sexo": "Hombre",
      "Q4 Nivel ingresos": "Medio",
      "Q5 Relacion con el vino": "Aficionado",
      "Q6 Compañia de viaje": "En pareja",
      "Q7 Noches en Jerez": "2-3 noches",
      "Q8 Frecuencia de visita": "Primera visita",
      "Q9 Actividades realizadas": "Visita a bodega / Cata",
      "Q10 Medio de transporte": "A pie desde el centro",
      "Q11 Alojamiento": "Apartamento turistico",
      "Q12 Oferta gastronomica": "Tapeo en el centro",
      "Q13 Gasto por persona (visita+cata)": "15-30€",
      "Q14 % gasto en vino/bodegas": "Entre 10-25%",
      "Q15 Medios de inspiracion": "Redes sociales / Web o App oficial de turismo",
      "Q16 Motivo principal de la visita": "El clima suave de invierno",
      "Q17 Destino alternativo": "Rioja",
      "Q18 Satisfaccion global (1-5)": 4,
      "Q19a Transporte/señalizacion (1-5)": 5,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 4,
      "Q19d Calidad-precio (1-5)": 3,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "La experiencia autentica en bodegas centenarias",
      "Q21 Aspecto a mejorar": "Reducir la masificacion en fechas de temporada alta (Navidad, vendimia, Feria)",
      "Q22 NPS (0-10)": 9,
      "Q23 Intencion de repetir": "No lo se"
    },
    {
      "ID": "R002",
      "Q1 Procedencia": "España - Cataluña",
      "Q2 Edad": "25-34",
      "Q3 Sexo": "Hombre",
      "Q4 Nivel ingresos": "Medio",
      "Q5 Relacion con el vino": "Aficionado",
      "Q6 Compañia de viaje": "Con amigos",
      "Q7 Noches en Jerez": "Excursion de un dia",
      "Q8 Frecuencia de visita": "He repetido en 1-2 ocasiones",
      "Q9 Actividades realizadas": "Otra",
      "Q10 Medio de transporte": "Coche propio o alquilado",
      "Q11 Alojamiento": "Hotel en el centro de Jerez",
      "Q12 Oferta gastronomica": "Compra de vino para llevar",
      "Q13 Gasto por persona (visita+cata)": "15-30€",
      "Q14 % gasto en vino/bodegas": "Mas del 50%",
      "Q15 Medios de inspiracion": "Agencia de viajes / Buscador de internet",
      "Q16 Motivo principal de la visita": "El vino y las bodegas",
      "Q17 Destino alternativo": "Ninguno, Jerez era mi unica opcion",
      "Q18 Satisfaccion global (1-5)": 5,
      "Q19a Transporte/señalizacion (1-5)": 5,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 5,
      "Q19d Calidad-precio (1-5)": 4,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "El precio de la visita en relacion a la calidad",
      "Q21 Aspecto a mejorar": "Mejor señalizacion para llegar a las bodegas mas alejadas",
      "Q22 NPS (0-10)": 9,
      "Q23 Intencion de repetir": "Si, seguro"
    },
    {
      "ID": "R003",
      "Q1 Procedencia": "Paises Bajos",
      "Q2 Edad": "65 o mas",
      "Q3 Sexo": "Hombre",
      "Q4 Nivel ingresos": "Alto",
      "Q5 Relacion con el vino": "Aficionado",
      "Q6 Compañia de viaje": "Con amigos",
      "Q7 Noches en Jerez": "4-7 noches",
      "Q8 Frecuencia de visita": "He repetido en 1-2 ocasiones",
      "Q9 Actividades realizadas": "Visita a bodega / Cata / Ruta a pie por viñedo o casco historico",
      "Q10 Medio de transporte": "Autobus turistico",
      "Q11 Alojamiento": "Otro municipio cercano (El Puerto, Sanlucar, Cadiz)",
      "Q12 Oferta gastronomica": "Tapeo en el centro",
      "Q13 Gasto por persona (visita+cata)": "Mas de 50€",
      "Q14 % gasto en vino/bodegas": "Menos del 10%",
      "Q15 Medios de inspiracion": "Agencia de viajes",
      "Q16 Motivo principal de la visita": "El vino y las bodegas",
      "Q17 Destino alternativo": "Rioja",
      "Q18 Satisfaccion global (1-5)": 3,
      "Q19a Transporte/señalizacion (1-5)": 4,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 3,
      "Q19d Calidad-precio (1-5)": 2,
      "Q19e Atencion en bodega (1-5)": 3,
      "Q20 Aspecto mas positivo": "La experiencia autentica en bodegas centenarias",
      "Q21 Aspecto a mejorar": "Precios mas asequibles en algunas experiencias",
      "Q22 NPS (0-10)": 6,
      "Q23 Intencion de repetir": "Si, seguro"
    },
    {
      "ID": "R004",
      "Q1 Procedencia": "España - Madrid",
      "Q2 Edad": "45-54",
      "Q3 Sexo": "Mujer",
      "Q4 Nivel ingresos": "Medio",
      "Q5 Relacion con el vino": "Sin relacion particular",
      "Q6 Compañia de viaje": "Solo/a",
      "Q7 Noches en Jerez": "1 noche",
      "Q8 Frecuencia de visita": "Primera visita",
      "Q9 Actividades realizadas": "Espectaculo ecuestre / Visita a bodega / Cata",
      "Q10 Medio de transporte": "Coche propio o alquilado",
      "Q11 Alojamiento": "Hotel-bodega o alojamiento rural en el Marco de Jerez",
      "Q12 Oferta gastronomica": "Restaurante con menu maridado",
      "Q13 Gasto por persona (visita+cata)": "Menos de 15€",
      "Q14 % gasto en vino/bodegas": "Entre 10-25%",
      "Q15 Medios de inspiracion": "Buscador de internet / Web o App oficial de turismo",
      "Q16 Motivo principal de la visita": "El Alcazar, la Catedral o el patrimonio",
      "Q17 Destino alternativo": "Ribera del Duero",
      "Q18 Satisfaccion global (1-5)": 4,
      "Q19a Transporte/señalizacion (1-5)": 3,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 4,
      "Q19d Calidad-precio (1-5)": 3,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "La tranquilidad y el trato personalizado en grupos pequeños",
      "Q21 Aspecto a mejorar": "Reducir la masificacion en fechas de temporada alta (Navidad, vendimia, Feria)",
      "Q22 NPS (0-10)": 8,
      "Q23 Intencion de repetir": "No lo se"
    },
    {
      "ID": "R005",
      "Q1 Procedencia": "España - Andalucia",
      "Q2 Edad": "45-54",
      "Q3 Sexo": "Mujer",
      "Q4 Nivel ingresos": "Medio",
      "Q5 Relacion con el vino": "Aficionado",
      "Q6 Compañia de viaje": "En familia con niños",
      "Q7 Noches en Jerez": "2-3 noches",
      "Q8 Frecuencia de visita": "He repetido en 1-2 ocasiones",
      "Q9 Actividades realizadas": "Ruta a pie por viñedo o casco historico / Cata / Compra en tienda de vinos",
      "Q10 Medio de transporte": "A pie desde el centro",
      "Q11 Alojamiento": "Hotel en el centro de Jerez",
      "Q12 Oferta gastronomica": "Restaurante con menu maridado",
      "Q13 Gasto por persona (visita+cata)": "15-30€",
      "Q14 % gasto en vino/bodegas": "Entre 10-25%",
      "Q15 Medios de inspiracion": "Redes sociales / Buscador de internet",
      "Q16 Motivo principal de la visita": "El clima suave de invierno",
      "Q17 Destino alternativo": "Ribera del Duero",
      "Q18 Satisfaccion global (1-5)": 5,
      "Q19a Transporte/señalizacion (1-5)": 4,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 5,
      "Q19d Calidad-precio (1-5)": 3,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "Aprender sobre el proceso de crianza en soleras",
      "Q21 Aspecto a mejorar": "Mas aparcamiento cerca de las bodegas",
      "Q22 NPS (0-10)": 10,
      "Q23 Intencion de repetir": "Si, seguro"
    },
    {
      "ID": "R006",
      "Q1 Procedencia": "España - otra CCAA",
      "Q2 Edad": "45-54",
      "Q3 Sexo": "Mujer",
      "Q4 Nivel ingresos": "Medio-bajo",
      "Q5 Relacion con el vino": "Sin relacion particular",
      "Q6 Compañia de viaje": "En grupo organizado",
      "Q7 Noches en Jerez": "2-3 noches",
      "Q8 Frecuencia de visita": "He repetido en 1-2 ocasiones",
      "Q9 Actividades realizadas": "Cata",
      "Q10 Medio de transporte": "Coche propio o alquilado",
      "Q11 Alojamiento": "Hotel en el centro de Jerez",
      "Q12 Oferta gastronomica": "Restaurante con menu maridado",
      "Q13 Gasto por persona (visita+cata)": "15-30€",
      "Q14 % gasto en vino/bodegas": "Entre 25-50%",
      "Q15 Medios de inspiracion": "Web o App oficial de turismo",
      "Q16 Motivo principal de la visita": "La gastronomia",
      "Q17 Destino alternativo": "Otro destino de vino en España",
      "Q18 Satisfaccion global (1-5)": 4,
      "Q19a Transporte/señalizacion (1-5)": 3,
      "Q19b Alojamiento (1-5)": 4,
      "Q19c Gastronomia (1-5)": 5,
      "Q19d Calidad-precio (1-5)": 3,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "El precio de la visita en relacion a la calidad",
      "Q21 Aspecto a mejorar": "Mas transporte publico entre bodegas",
      "Q22 NPS (0-10)": 9,
      "Q23 Intencion de repetir": "Si, seguro"
    },
    {
      "ID": "R007",
      "Q1 Procedencia": "España - Andalucia",
      "Q2 Edad": "25-34",
      "Q3 Sexo": "Mujer",
      "Q4 Nivel ingresos": "Medio-alto",
      "Q5 Relacion con el vino": "Profesional del turismo",
      "Q6 Compañia de viaje": "En grupo organizado",
      "Q7 Noches en Jerez": "2-3 noches",
      "Q8 Frecuencia de visita": "He repetido en 1-2 ocasiones",
      "Q9 Actividades realizadas": "Compra en tienda de vinos",
      "Q10 Medio de transporte": "Coche propio o alquilado",
      "Q11 Alojamiento": "Apartamento turistico",
      "Q12 Oferta gastronomica": "Compra de vino para llevar",
      "Q13 Gasto por persona (visita+cata)": "15-30€",
      "Q14 % gasto en vino/bodegas": "Menos del 10%",
      "Q15 Medios de inspiracion": "Agencia de viajes",
      "Q16 Motivo principal de la visita": "La gastronomia",
      "Q17 Destino alternativo": "Otro destino de vino fuera de España",
      "Q18 Satisfaccion global (1-5)": 5,
      "Q19a Transporte/señalizacion (1-5)": 5,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 5,
      "Q19d Calidad-precio (1-5)": 3,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "Aprender sobre el proceso de crianza en soleras",
      "Q21 Aspecto a mejorar": "Mejor conexion entre el centro y las bodegas rurales",
      "Q22 NPS (0-10)": 9,
      "Q23 Intencion de repetir": "Si, seguro"
    },
    {
      "ID": "R008",
      "Q1 Procedencia": "España - otra CCAA",
      "Q2 Edad": "65 o mas",
      "Q3 Sexo": "Hombre",
      "Q4 Nivel ingresos": "Medio",
      "Q5 Relacion con el vino": "Aficionado",
      "Q6 Compañia de viaje": "En pareja",
      "Q7 Noches en Jerez": "2-3 noches",
      "Q8 Frecuencia de visita": "He repetido en 1-2 ocasiones",
      "Q9 Actividades realizadas": "Maridaje o comida en bodega / Otra / Cata",
      "Q10 Medio de transporte": "A pie desde el centro",
      "Q11 Alojamiento": "Hotel en el centro de Jerez",
      "Q12 Oferta gastronomica": "Tapeo en el centro",
      "Q13 Gasto por persona (visita+cata)": "31-50€",
      "Q14 % gasto en vino/bodegas": "Mas del 50%",
      "Q15 Medios de inspiracion": "Redes sociales / Web o App oficial de turismo",
      "Q16 Motivo principal de la visita": "La Real Escuela del Arte Ecuestre",
      "Q17 Destino alternativo": "Otro destino de vino en España",
      "Q18 Satisfaccion global (1-5)": 4,
      "Q19a Transporte/señalizacion (1-5)": 4,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 4,
      "Q19d Calidad-precio (1-5)": 2,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "El ambiente y la arquitectura de las bodegas",
      "Q21 Aspecto a mejorar": "Reducir la masificacion en fechas de temporada alta (Navidad, vendimia, Feria)",
      "Q22 NPS (0-10)": 9,
      "Q23 Intencion de repetir": "No lo se"
    },
    {
      "ID": "R009",
      "Q1 Procedencia": "Reino Unido",
      "Q2 Edad": "55-64",
      "Q3 Sexo": "Hombre",
      "Q4 Nivel ingresos": "Medio-alto",
      "Q5 Relacion con el vino": "Aficionado",
      "Q6 Compañia de viaje": "En pareja",
      "Q7 Noches en Jerez": "Excursion de un dia",
      "Q8 Frecuencia de visita": "Vengo con regularidad (3 o mas veces)",
      "Q9 Actividades realizadas": "Compra en tienda de vinos / Visita a bodega",
      "Q10 Medio de transporte": "Coche propio o alquilado",
      "Q11 Alojamiento": "Hotel en el centro de Jerez",
      "Q12 Oferta gastronomica": "Compra de vino para llevar",
      "Q13 Gasto por persona (visita+cata)": "15-30€",
      "Q14 % gasto en vino/bodegas": "Entre 25-50%",
      "Q15 Medios de inspiracion": "Recomendacion de amigos o familia / Prensa o influencers",
      "Q16 Motivo principal de la visita": "El clima suave de invierno",
      "Q17 Destino alternativo": "Ninguno, Jerez era mi unica opcion",
      "Q18 Satisfaccion global (1-5)": 4,
      "Q19a Transporte/señalizacion (1-5)": 4,
      "Q19b Alojamiento (1-5)": 4,
      "Q19c Gastronomia (1-5)": 4,
      "Q19d Calidad-precio (1-5)": 3,
      "Q19e Atencion en bodega (1-5)": 4,
      "Q20 Aspecto mas positivo": "El patrimonio historico del centro de Jerez",
      "Q21 Aspecto a mejorar": "Mejor señalizacion para llegar a las bodegas mas alejadas",
      "Q22 NPS (0-10)": 7,
      "Q23 Intencion de repetir": "Si, seguro"
    },
    {
      "ID": "R010",
      "Q1 Procedencia": "España - Cataluña",
      "Q2 Edad": "35-44",
      "Q3 Sexo": "Mujer",
      "Q4 Nivel ingresos": "Medio",
      "Q5 Relacion con el vino": "Aficionado",
      "Q6 Compañia de viaje": "En familia con niños",
      "Q7 Noches en Jerez": "2-3 noches",
      "Q8 Frecuencia de visita": "Primera visita",
      "Q9 Actividades realizadas": "Visita a bodega / Compra en tienda de vinos / Ruta a pie por viñedo o casco historico",
      "Q10 Medio de transporte": "Autobus turistico",
      "Q11 Alojamiento": "Hotel en el centro de Jerez",
      "Q12 Oferta gastronomica": "Ninguna en particular",
      "Q13 Gasto por persona (visita+cata)": "31-50€",
      "Q14 % gasto en vino/bodegas": "Entre 25-50%",
      "Q15 Medios de inspiracion": "Recomendacion de amigos o familia / Web o App oficial de turismo",
      "Q16 Motivo principal de la visita": "El vino y las bodegas",
      "Q17 Destino alternativo": "Otro destino de vino en España",
      "Q18 Satisfaccion global (1-5)": 5,
      "Q19a Transporte/señalizacion (1-5)": 5,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 5,
      "Q19d Calidad-precio (1-5)": 4,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "El precio de la visita en relacion a la calidad",
      "Q21 Aspecto a mejorar": "Mejor señalizacion para llegar a las bodegas mas alejadas",
      "Q22 NPS (0-10)": 7,
      "Q23 Intencion de repetir": "Probablemente si"
    },
    {
      "ID": "R011",
      "Q1 Procedencia": "Reino Unido",
      "Q2 Edad": "25-34",
      "Q3 Sexo": "Mujer",
      "Q4 Nivel ingresos": "Medio-alto",
      "Q5 Relacion con el vino": "Profesional del turismo",
      "Q6 Compañia de viaje": "En pareja",
      "Q7 Noches en Jerez": "4-7 noches",
      "Q8 Frecuencia de visita": "Primera visita",
      "Q9 Actividades realizadas": "Compra en tienda de vinos",
      "Q10 Medio de transporte": "Autobus turistico",
      "Q11 Alojamiento": "Hotel en el centro de Jerez",
      "Q12 Oferta gastronomica": "Restaurante con menu maridado",
      "Q13 Gasto por persona (visita+cata)": "15-30€",
      "Q14 % gasto en vino/bodegas": "Mas del 50%",
      "Q15 Medios de inspiracion": "Agencia de viajes",
      "Q16 Motivo principal de la visita": "El clima suave de invierno",
      "Q17 Destino alternativo": "Otro destino de vino fuera de España",
      "Q18 Satisfaccion global (1-5)": 4,
      "Q19a Transporte/señalizacion (1-5)": 4,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 3,
      "Q19d Calidad-precio (1-5)": 4,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "El precio de la visita en relacion a la calidad",
      "Q21 Aspecto a mejorar": "Mejor conexion entre el centro y las bodegas rurales",
      "Q22 NPS (0-10)": 9,
      "Q23 Intencion de repetir": "Si, seguro"
    },
    {
      "ID": "R012",
      "Q1 Procedencia": "Estados Unidos",
      "Q2 Edad": "55-64",
      "Q3 Sexo": "Mujer",
      "Q4 Nivel ingresos": "Medio-alto",
      "Q5 Relacion con el vino": "Profesional del turismo",
      "Q6 Compañia de viaje": "En pareja",
      "Q7 Noches en Jerez": "1 noche",
      "Q8 Frecuencia de visita": "He repetido en 1-2 ocasiones",
      "Q9 Actividades realizadas": "Visita a bodega / Compra en tienda de vinos / Maridaje o comida en bodega",
      "Q10 Medio de transporte": "Coche propio o alquilado",
      "Q11 Alojamiento": "Apartamento turistico",
      "Q12 Oferta gastronomica": "Tapeo en el centro",
      "Q13 Gasto por persona (visita+cata)": "31-50€",
      "Q14 % gasto en vino/bodegas": "Entre 25-50%",
      "Q15 Medios de inspiracion": "Web o App oficial de turismo",
      "Q16 Motivo principal de la visita": "El Alcazar, la Catedral o el patrimonio",
      "Q17 Destino alternativo": "Otro destino de vino fuera de España",
      "Q18 Satisfaccion global (1-5)": 4,
      "Q19a Transporte/señalizacion (1-5)": 3,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 4,
      "Q19d Calidad-precio (1-5)": 3,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "El ambiente y la arquitectura de las bodegas",
      "Q21 Aspecto a mejorar": "Horarios de visita mas flexibles",
      "Q22 NPS (0-10)": 8,
      "Q23 Intencion de repetir": "Probablemente si"
    },
    {
      "ID": "R013",
      "Q1 Procedencia": "España - Andalucia",
      "Q2 Edad": "25-34",
      "Q3 Sexo": "Mujer",
      "Q4 Nivel ingresos": "Alto",
      "Q5 Relacion con el vino": "Profesional del turismo",
      "Q6 Compañia de viaje": "En pareja",
      "Q7 Noches en Jerez": "Excursion de un dia",
      "Q8 Frecuencia de visita": "Vengo con regularidad (3 o mas veces)",
      "Q9 Actividades realizadas": "Visita a bodega",
      "Q10 Medio de transporte": "A pie desde el centro",
      "Q11 Alojamiento": "Otro municipio cercano (El Puerto, Sanlucar, Cadiz)",
      "Q12 Oferta gastronomica": "Tapeo en el centro",
      "Q13 Gasto por persona (visita+cata)": "31-50€",
      "Q14 % gasto en vino/bodegas": "Mas del 50%",
      "Q15 Medios de inspiracion": "Recomendacion de amigos o familia",
      "Q16 Motivo principal de la visita": "El vino y las bodegas",
      "Q17 Destino alternativo": "Rioja",
      "Q18 Satisfaccion global (1-5)": 4,
      "Q19a Transporte/señalizacion (1-5)": 5,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 4,
      "Q19d Calidad-precio (1-5)": 3,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "La experiencia autentica en bodegas centenarias",
      "Q21 Aspecto a mejorar": "Ampliar los horarios de tarde en invierno",
      "Q22 NPS (0-10)": 8,
      "Q23 Intencion de repetir": "Si, seguro"
    },
    {
      "ID": "R014",
      "Q1 Procedencia": "Otro pais",
      "Q2 Edad": "35-44",
      "Q3 Sexo": "Mujer",
      "Q4 Nivel ingresos": "Alto",
      "Q5 Relacion con el vino": "Profesional del vino",
      "Q6 Compañia de viaje": "En pareja",
      "Q7 Noches en Jerez": "Excursion de un dia",
      "Q8 Frecuencia de visita": "Primera visita",
      "Q9 Actividades realizadas": "Visita a bodega",
      "Q10 Medio de transporte": "Coche propio o alquilado",
      "Q11 Alojamiento": "No pernocto",
      "Q12 Oferta gastronomica": "Tapeo en el centro",
      "Q13 Gasto por persona (visita+cata)": "Menos de 15€",
      "Q14 % gasto en vino/bodegas": "Entre 10-25%",
      "Q15 Medios de inspiracion": "Agencia de viajes / Web o App oficial de turismo",
      "Q16 Motivo principal de la visita": "El vino y las bodegas",
      "Q17 Destino alternativo": "Rioja",
      "Q18 Satisfaccion global (1-5)": 5,
      "Q19a Transporte/señalizacion (1-5)": 5,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 5,
      "Q19d Calidad-precio (1-5)": 3,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "Aprender sobre el proceso de crianza en soleras",
      "Q21 Aspecto a mejorar": "Mas aparcamiento cerca de las bodegas",
      "Q22 NPS (0-10)": 10,
      "Q23 Intencion de repetir": "No lo se"
    },
    {
      "ID": "R015",
      "Q1 Procedencia": "España - otra CCAA",
      "Q2 Edad": "45-54",
      "Q3 Sexo": "Hombre",
      "Q4 Nivel ingresos": "Medio",
      "Q5 Relacion con el vino": "Aficionado",
      "Q6 Compañia de viaje": "Solo/a",
      "Q7 Noches en Jerez": "2-3 noches",
      "Q8 Frecuencia de visita": "Vengo con regularidad (3 o mas veces)",
      "Q9 Actividades realizadas": "Visita a bodega / Ruta a pie por viñedo o casco historico / Espectaculo ecuestre",
      "Q10 Medio de transporte": "Coche propio o alquilado",
      "Q11 Alojamiento": "Hotel en el centro de Jerez",
      "Q12 Oferta gastronomica": "Tapeo en el centro",
      "Q13 Gasto por persona (visita+cata)": "31-50€",
      "Q14 % gasto en vino/bodegas": "Entre 10-25%",
      "Q15 Medios de inspiracion": "Buscador de internet / Agencia de viajes",
      "Q16 Motivo principal de la visita": "El Alcazar, la Catedral o el patrimonio",
      "Q17 Destino alternativo": "Ribera del Duero",
      "Q18 Satisfaccion global (1-5)": 5,
      "Q19a Transporte/señalizacion (1-5)": 5,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 5,
      "Q19d Calidad-precio (1-5)": 3,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "La tranquilidad y el trato personalizado en grupos pequeños",
      "Q21 Aspecto a mejorar": "Mas actividades para familias con niños",
      "Q22 NPS (0-10)": 8,
      "Q23 Intencion de repetir": "Probablemente si"
    },
    {
      "ID": "R016",
      "Q1 Procedencia": "España - otra CCAA",
      "Q2 Edad": "35-44",
      "Q3 Sexo": "Hombre",
      "Q4 Nivel ingresos": "Medio",
      "Q5 Relacion con el vino": "Profesional del turismo",
      "Q6 Compañia de viaje": "En grupo organizado",
      "Q7 Noches en Jerez": "Excursion de un dia",
      "Q8 Frecuencia de visita": "He repetido en 1-2 ocasiones",
      "Q9 Actividades realizadas": "Cata / Visita a bodega",
      "Q10 Medio de transporte": "Autobus turistico",
      "Q11 Alojamiento": "Hotel en el centro de Jerez",
      "Q12 Oferta gastronomica": "Restaurante con menu maridado",
      "Q13 Gasto por persona (visita+cata)": "Mas de 50€",
      "Q14 % gasto en vino/bodegas": "Menos del 10%",
      "Q15 Medios de inspiracion": "Redes sociales / Agencia de viajes",
      "Q16 Motivo principal de la visita": "El vino y las bodegas",
      "Q17 Destino alternativo": "Otro destino de vino en España",
      "Q18 Satisfaccion global (1-5)": 5,
      "Q19a Transporte/señalizacion (1-5)": 5,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 5,
      "Q19d Calidad-precio (1-5)": 3,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "El patrimonio historico del centro de Jerez",
      "Q21 Aspecto a mejorar": "Ampliar los horarios de tarde en invierno",
      "Q22 NPS (0-10)": 10,
      "Q23 Intencion de repetir": "Probablemente si"
    },
    {
      "ID": "R017",
      "Q1 Procedencia": "España - Madrid",
      "Q2 Edad": "35-44",
      "Q3 Sexo": "Mujer",
      "Q4 Nivel ingresos": "Medio-alto",
      "Q5 Relacion con el vino": "Aficionado",
      "Q6 Compañia de viaje": "Solo/a",
      "Q7 Noches en Jerez": "2-3 noches",
      "Q8 Frecuencia de visita": "Primera visita",
      "Q9 Actividades realizadas": "Cata / Ruta a pie por viñedo o casco historico",
      "Q10 Medio de transporte": "A pie desde el centro",
      "Q11 Alojamiento": "Hotel en el centro de Jerez",
      "Q12 Oferta gastronomica": "Tapeo en el centro",
      "Q13 Gasto por persona (visita+cata)": "Mas de 50€",
      "Q14 % gasto en vino/bodegas": "Entre 25-50%",
      "Q15 Medios de inspiracion": "Redes sociales",
      "Q16 Motivo principal de la visita": "El vino y las bodegas",
      "Q17 Destino alternativo": "Ribera del Duero",
      "Q18 Satisfaccion global (1-5)": 4,
      "Q19a Transporte/señalizacion (1-5)": 4,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 3,
      "Q19d Calidad-precio (1-5)": 4,
      "Q19e Atencion en bodega (1-5)": 4,
      "Q20 Aspecto mas positivo": "El ambiente y la arquitectura de las bodegas",
      "Q21 Aspecto a mejorar": "Ampliar los horarios de tarde en invierno",
      "Q22 NPS (0-10)": 8,
      "Q23 Intencion de repetir": "Si, seguro"
    },
    {
      "ID": "R018",
      "Q1 Procedencia": "Alemania",
      "Q2 Edad": "35-44",
      "Q3 Sexo": "Mujer",
      "Q4 Nivel ingresos": "Medio-alto",
      "Q5 Relacion con el vino": "Aficionado",
      "Q6 Compañia de viaje": "En pareja",
      "Q7 Noches en Jerez": "2-3 noches",
      "Q8 Frecuencia de visita": "Primera visita",
      "Q9 Actividades realizadas": "Cata / Compra en tienda de vinos / Visita a bodega",
      "Q10 Medio de transporte": "A pie desde el centro",
      "Q11 Alojamiento": "Hotel en el centro de Jerez",
      "Q12 Oferta gastronomica": "Tapeo en el centro",
      "Q13 Gasto por persona (visita+cata)": "Menos de 15€",
      "Q14 % gasto en vino/bodegas": "Entre 25-50%",
      "Q15 Medios de inspiracion": "Web o App oficial de turismo / Buscador de internet",
      "Q16 Motivo principal de la visita": "La gastronomia",
      "Q17 Destino alternativo": "Ninguno, Jerez era mi unica opcion",
      "Q18 Satisfaccion global (1-5)": 4,
      "Q19a Transporte/señalizacion (1-5)": 3,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 4,
      "Q19d Calidad-precio (1-5)": 3,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "El trato cercano del personal de bodega",
      "Q21 Aspecto a mejorar": "Mas informacion en ingles y otros idiomas",
      "Q22 NPS (0-10)": 10,
      "Q23 Intencion de repetir": "Si, seguro"
    },
    {
      "ID": "R019",
      "Q1 Procedencia": "España - Andalucia",
      "Q2 Edad": "45-54",
      "Q3 Sexo": "Hombre",
      "Q4 Nivel ingresos": "Medio-alto",
      "Q5 Relacion con el vino": "Aficionado",
      "Q6 Compañia de viaje": "Con amigos",
      "Q7 Noches en Jerez": "2-3 noches",
      "Q8 Frecuencia de visita": "Primera visita",
      "Q9 Actividades realizadas": "Visita a bodega / Compra en tienda de vinos / Ruta a pie por viñedo o casco historico",
      "Q10 Medio de transporte": "Taxi o VTC",
      "Q11 Alojamiento": "Otro municipio cercano (El Puerto, Sanlucar, Cadiz)",
      "Q12 Oferta gastronomica": "Tapeo en el centro",
      "Q13 Gasto por persona (visita+cata)": "15-30€",
      "Q14 % gasto en vino/bodegas": "Menos del 10%",
      "Q15 Medios de inspiracion": "Web o App oficial de turismo / Redes sociales",
      "Q16 Motivo principal de la visita": "La gastronomia",
      "Q17 Destino alternativo": "Sanlucar de Barrameda o El Puerto de Santa Maria",
      "Q18 Satisfaccion global (1-5)": 5,
      "Q19a Transporte/señalizacion (1-5)": 5,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 5,
      "Q19d Calidad-precio (1-5)": 3,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "El trato cercano del personal de bodega",
      "Q21 Aspecto a mejorar": "Mejor conexion entre el centro y las bodegas rurales",
      "Q22 NPS (0-10)": 10,
      "Q23 Intencion de repetir": "Probablemente si"
    },
    {
      "ID": "R020",
      "Q1 Procedencia": "Reino Unido",
      "Q2 Edad": "18-24",
      "Q3 Sexo": "Hombre",
      "Q4 Nivel ingresos": "Medio-alto",
      "Q5 Relacion con el vino": "Aficionado",
      "Q6 Compañia de viaje": "En familia con niños",
      "Q7 Noches en Jerez": "2-3 noches",
      "Q8 Frecuencia de visita": "Primera visita",
      "Q9 Actividades realizadas": "Compra en tienda de vinos",
      "Q10 Medio de transporte": "A pie desde el centro",
      "Q11 Alojamiento": "Hotel en el centro de Jerez",
      "Q12 Oferta gastronomica": "Tapeo en el centro",
      "Q13 Gasto por persona (visita+cata)": "31-50€",
      "Q14 % gasto en vino/bodegas": "Entre 25-50%",
      "Q15 Medios de inspiracion": "Web o App oficial de turismo",
      "Q16 Motivo principal de la visita": "El vino y las bodegas",
      "Q17 Destino alternativo": "Rioja",
      "Q18 Satisfaccion global (1-5)": 4,
      "Q19a Transporte/señalizacion (1-5)": 3,
      "Q19b Alojamiento (1-5)": 4,
      "Q19c Gastronomia (1-5)": 3,
      "Q19d Calidad-precio (1-5)": 3,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "La experiencia autentica en bodegas centenarias",
      "Q21 Aspecto a mejorar": "Mas actividades para familias con niños",
      "Q22 NPS (0-10)": 9,
      "Q23 Intencion de repetir": "Si, seguro"
    },
    {
      "ID": "R021",
      "Q1 Procedencia": "Reino Unido",
      "Q2 Edad": "55-64",
      "Q3 Sexo": "Mujer",
      "Q4 Nivel ingresos": "Medio-bajo",
      "Q5 Relacion con el vino": "Aficionado",
      "Q6 Compañia de viaje": "En pareja",
      "Q7 Noches en Jerez": "2-3 noches",
      "Q8 Frecuencia de visita": "Primera visita",
      "Q9 Actividades realizadas": "Espectaculo ecuestre",
      "Q10 Medio de transporte": "Coche propio o alquilado",
      "Q11 Alojamiento": "Apartamento turistico",
      "Q12 Oferta gastronomica": "Compra de vino para llevar",
      "Q13 Gasto por persona (visita+cata)": "15-30€",
      "Q14 % gasto en vino/bodegas": "Menos del 10%",
      "Q15 Medios de inspiracion": "Prensa o influencers",
      "Q16 Motivo principal de la visita": "El flamenco",
      "Q17 Destino alternativo": "Otro destino de vino en España",
      "Q18 Satisfaccion global (1-5)": 4,
      "Q19a Transporte/señalizacion (1-5)": 4,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 3,
      "Q19d Calidad-precio (1-5)": 2,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "El precio de la visita en relacion a la calidad",
      "Q21 Aspecto a mejorar": "Mas transporte publico entre bodegas",
      "Q22 NPS (0-10)": 10,
      "Q23 Intencion de repetir": "Probablemente no"
    },
    {
      "ID": "R022",
      "Q1 Procedencia": "Francia",
      "Q2 Edad": "35-44",
      "Q3 Sexo": "Mujer",
      "Q4 Nivel ingresos": "Medio",
      "Q5 Relacion con el vino": "Aficionado",
      "Q6 Compañia de viaje": "En pareja",
      "Q7 Noches en Jerez": "2-3 noches",
      "Q8 Frecuencia de visita": "Vengo con regularidad (3 o mas veces)",
      "Q9 Actividades realizadas": "Maridaje o comida en bodega / Visita a bodega",
      "Q10 Medio de transporte": "Coche propio o alquilado",
      "Q11 Alojamiento": "No pernocto",
      "Q12 Oferta gastronomica": "Tapeo en el centro",
      "Q13 Gasto por persona (visita+cata)": "Menos de 15€",
      "Q14 % gasto en vino/bodegas": "Entre 25-50%",
      "Q15 Medios de inspiracion": "Web o App oficial de turismo",
      "Q16 Motivo principal de la visita": "La Real Escuela del Arte Ecuestre",
      "Q17 Destino alternativo": "Rioja",
      "Q18 Satisfaccion global (1-5)": 5,
      "Q19a Transporte/señalizacion (1-5)": 5,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 5,
      "Q19d Calidad-precio (1-5)": 5,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "El precio de la visita en relacion a la calidad",
      "Q21 Aspecto a mejorar": "Precios mas asequibles en algunas experiencias",
      "Q22 NPS (0-10)": 10,
      "Q23 Intencion de repetir": "Probablemente si"
    },
    {
      "ID": "R023",
      "Q1 Procedencia": "España - Madrid",
      "Q2 Edad": "25-34",
      "Q3 Sexo": "Mujer",
      "Q4 Nivel ingresos": "Medio",
      "Q5 Relacion con el vino": "Profesional del turismo",
      "Q6 Compañia de viaje": "En pareja",
      "Q7 Noches en Jerez": "Excursion de un dia",
      "Q8 Frecuencia de visita": "Primera visita",
      "Q9 Actividades realizadas": "Visita a bodega / Maridaje o comida en bodega",
      "Q10 Medio de transporte": "Coche propio o alquilado",
      "Q11 Alojamiento": "Apartamento turistico",
      "Q12 Oferta gastronomica": "Restaurante con menu maridado",
      "Q13 Gasto por persona (visita+cata)": "15-30€",
      "Q14 % gasto en vino/bodegas": "Mas del 50%",
      "Q15 Medios de inspiracion": "Redes sociales / Recomendacion de amigos o familia",
      "Q16 Motivo principal de la visita": "El vino y las bodegas",
      "Q17 Destino alternativo": "Ninguno, Jerez era mi unica opcion",
      "Q18 Satisfaccion global (1-5)": 4,
      "Q19a Transporte/señalizacion (1-5)": 4,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 4,
      "Q19d Calidad-precio (1-5)": 4,
      "Q19e Atencion en bodega (1-5)": 4,
      "Q20 Aspecto mas positivo": "El ambiente y la arquitectura de las bodegas",
      "Q21 Aspecto a mejorar": "Horarios de visita mas flexibles",
      "Q22 NPS (0-10)": 8,
      "Q23 Intencion de repetir": "Si, seguro"
    },
    {
      "ID": "R024",
      "Q1 Procedencia": "España - otra CCAA",
      "Q2 Edad": "35-44",
      "Q3 Sexo": "Hombre",
      "Q4 Nivel ingresos": "Medio-alto",
      "Q5 Relacion con el vino": "Sin relacion particular",
      "Q6 Compañia de viaje": "Solo/a",
      "Q7 Noches en Jerez": "Excursion de un dia",
      "Q8 Frecuencia de visita": "Primera visita",
      "Q9 Actividades realizadas": "Compra en tienda de vinos / Cata",
      "Q10 Medio de transporte": "Transporte publico regular",
      "Q11 Alojamiento": "Hotel en el centro de Jerez",
      "Q12 Oferta gastronomica": "Compra de vino para llevar",
      "Q13 Gasto por persona (visita+cata)": "Menos de 15€",
      "Q14 % gasto en vino/bodegas": "Mas del 50%",
      "Q15 Medios de inspiracion": "Redes sociales / Web o App oficial de turismo",
      "Q16 Motivo principal de la visita": "El flamenco",
      "Q17 Destino alternativo": "Ninguno, Jerez era mi unica opcion",
      "Q18 Satisfaccion global (1-5)": 5,
      "Q19a Transporte/señalizacion (1-5)": 4,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 5,
      "Q19d Calidad-precio (1-5)": 4,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "El espectaculo ecuestre",
      "Q21 Aspecto a mejorar": "Reducir la masificacion en fechas de temporada alta (Navidad, vendimia, Feria)",
      "Q22 NPS (0-10)": 8,
      "Q23 Intencion de repetir": "Probablemente si"
    },
    {
      "ID": "R025",
      "Q1 Procedencia": "Otro pais",
      "Q2 Edad": "25-34",
      "Q3 Sexo": "Hombre",
      "Q4 Nivel ingresos": "Medio-alto",
      "Q5 Relacion con el vino": "Profesional del vino",
      "Q6 Compañia de viaje": "Con amigos",
      "Q7 Noches en Jerez": "2-3 noches",
      "Q8 Frecuencia de visita": "Vengo con regularidad (3 o mas veces)",
      "Q9 Actividades realizadas": "Espectaculo ecuestre / Maridaje o comida en bodega",
      "Q10 Medio de transporte": "Coche propio o alquilado",
      "Q11 Alojamiento": "No pernocto",
      "Q12 Oferta gastronomica": "Compra de vino para llevar",
      "Q13 Gasto por persona (visita+cata)": "15-30€",
      "Q14 % gasto en vino/bodegas": "Entre 25-50%",
      "Q15 Medios de inspiracion": "Web o App oficial de turismo",
      "Q16 Motivo principal de la visita": "El clima suave de invierno",
      "Q17 Destino alternativo": "Ribera del Duero",
      "Q18 Satisfaccion global (1-5)": 5,
      "Q19a Transporte/señalizacion (1-5)": 5,
      "Q19b Alojamiento (1-5)": 5,
      "Q19c Gastronomia (1-5)": 5,
      "Q19d Calidad-precio (1-5)": 5,
      "Q19e Atencion en bodega (1-5)": 5,
      "Q20 Aspecto mas positivo": "El espectaculo ecuestre",
      "Q21 Aspecto a mejorar": "Horarios de visita mas flexibles",
      "Q22 NPS (0-10)": 9,
      "Q23 Intencion de repetir": "Probablemente si"
    }
  ]
};
